language: ruby
rvm:
  - "2.0.0"

env:
  - DB=postgresql

script: xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rspec

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database histvest_test' -U postgres
  - bundle exec rake db:drop db:create db:migrate db:seed